require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

install! 'cocoapods',
  :deterministic_uuids => false

target 'allin_interior' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'rn-fetch-blob',
    :path => '../node_modules/rn-fetch-blob'

  pod 'Firebase/Auth'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
 
  target 'allin_interiorTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'allin_interior-tvOS' do
  # Pods for allin_interior-tvOS

  target 'allin_interior-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
